
version: '3.1'

services:
  dailyapp:
    container_name: todo_react
    image: todo_react
    restart: always
    image: daily
    build: ./
    ports:
      - "5555:4444"
    networks:
      - todo_default
    depends_on:
      - "PostgreSQL"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/todo
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  PostgreSQL:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog

networks:
  blog_default:
    name: todo_default
    driver: bridge